=== Oualid-jennani/Exercises_Html_Css_Javascript/5 - Exercises(Html,Css,Javascript,XML,DTD,XSD,XPATH,XSLT)/Série 10/S10DTD.dtd
<!ELEMENT stagiaires (stagiaire+)>
<!ELEMENT stagiaire (nom,prenom,telephone,email,adresse,stages*)>
<!ATTLIST stagiaire filiere CDATA #REQUIRED> 
<!ATTLIST stagiaire groupe CDATA #IMPLIED>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT adresse (#PCDATA)>
<!ELEMENT stages (dateDebut,dateFin,encadrant?,organisme)>
<!ELEMENT dateDebut (#PCDATA)>
<!ELEMENT dateFin (#PCDATA)>
<!ELEMENT encadrant (nom,prenom,telephone,email)>
<!ELEMENT organisme (nom,(adresse | telephone))>
<!ATTLIST organisme secteur (prive|public) "prive">

=== Oualid-jennani/Exercises_Html_Css_Javascript/5 - Exercises(Html,Css,Javascript,XML,DTD,XSD,XPATH,XSLT)/Série 10/Série 10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stagiaires SYSTEM "S10DTD.dtd">
<stagiaires>
    <stagiaire filiere ="TDI" groupe ="202">
        <nom> </nom>
        <prenom></prenom>
        <telephone></telephone>
        <email> </email>
        <adresse></adresse> 
        <stages>
          <dateDebut> </dateDebut>
          <dateFin></dateFin>
          <encadrant>
             <nom></nom>
             <prenom></prenom>
              <telephone></telephone>
              <email> </email>
            </encadrant>
             <organisme secteur="public">
               <nom> </nom>
                <adresse></adresse> 
              </organisme>
        </stages>
    </stagiaire>
</stagiaires>
