=== Oualid-jennani/Exercises_Html_Css_Javascript/5 - Exercises(Html,Css,Javascript,XML,DTD,XSD,XPATH,XSLT)/Série 11/EX1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="commande">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ref" type="xs:string"/>
        <xs:element name="client">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nom-prenom" type="xs:string"/>
              <xs:element name="adresse" type="xs:string"/>
              <xs:element name="ville" type="xs:string"/>
              <xs:element name="pays" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="article" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titre" type="xs:string"/>
              <xs:element name="description" type="xs:string" minOccurs="0"/>
              <xs:element name="quantite" type="xs:positiveInteger"/>
              <xs:element name="prix" type="xs:decimal"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="idCommande" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Oualid-jennani/Exercises_Html_Css_Javascript/5 - Exercises(Html,Css,Javascript,XML,DTD,XSD,XPATH,XSLT)/Série 11/EX1.xml
<?xml version="1.0" encoding="UTF-8"?>
<commande xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" idCommande="1" xsi:noNamespaceSchemaLocation="EX1.xsd">
  <ref>produit</ref>
  <client>
    <nom-prenom>walid jennani</nom-prenom>
    <adresse>hay najd  3 2013</adresse>
    <ville>oujda</ville>
    <pays>maroc</pays>
  </client>
  <article>
    <titre>stylo</titre>
    <description>this is nice stylo</description>
    <quantite>55</quantite>
    <prix>5</prix>
  </article>
</commande>
